---
   - name: get oha_artifacts directory status
     stat: path="{{ oha_artifacts }}"
     register: ohaDir
     ignore_errors: True
         
   - file: "path={{ oha_artifacts }} recurse=yes state=directory mode=0777"
     when: ohaDir.stat.exists == False

   - name: Check profile script exists
     stat: path="{{ oha_artifacts }}/ohaProfile.sh"
     register: profile 
     ignore_errors: True   

   - debug: msg="Copy and deploy scripts if don't exists"
  
   - name: Include profile script
     template: 
       src: "roles/deploy/templates/ohaProfile.sh"
       dest: "{{ oha_artifacts }}"
     when: profile.stat.exists == False

 #  - name: Include profile script
#     template: 
#       src: "roles/deploy/templates/gravitonProfile.sh"
#       dest: "{{ oha_home }}"
#     when: profile.stat.exists == False and aws_env == "graviton"
     
   - lineinfile: dest="{{ ec2_home }}/.bash_profile" regexp="ohaProfile.sh" line="alias setenv='. {{ oha_artifacts }}/ohaProfile.sh'"


        