- hosts: all
  sudo: True 
  vars:
    node_type: 'standalone'
    cluster_name: 
    
    
  pre_tasks:
   - include_vars: ec2_vars/config.yml  
   - include_vars: ec2_vars/elasticConfig.yml   

  roles:
    - elasticsearch