---  
- hosts: localhost 
  gather_facts: false 
  tasks:  

    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ instanceid }}'
        region: us-west-2 
