---
# s3 role
   - debug: msg="Artifact Name {{ artifact }}"
   
   - name: get oha_artifacts directory status
     stat: path="{{ oha_artifacts }}"
     register: ohaDir
     ignore_errors: True
         
   - file: "path={{ oha_artifacts }} recurse=yes state=directory mode=0777"
     when: ohaDir.stat.exists == False
     
   - s3: bucket="{{ bucket_name }}"
       region="{{ region }}"
       aws_access_key="{{ aws_access_key }}"
       aws_secret_key="{{ aws_secret_key }}"
       object="{{ artifact }}"
       dest="{{ oha_artifacts }}/{{ artifact }}"
       mode=get
