---
 - name: Provision EC2 Box
   local_action:
     module: ec2
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: '{"Name":"{{ ec2_tag_Name }}","autoshutdown":"{{ ec2_tag_autoshutdown }}","user":"{{ ec2_tag_user }}" }'
     assign_public_ip: yes
     wait: true
     count: 1
     volumes: 
     - device_name: /dev/sda1
       device_type: gp2
       volume_size: "{{ ec2_volume_size }}"
       delete_on_termination: true
    with_items:
      - master
      - worker
   register: ec2_

 - debug: var=item
   with_items: ec2.instances

 - add_host: name={{ item.public_ip }} >
             ec2_region={{ ec2_region }} 
             ec2_tag_Name={{ ec2_tag_Name }}
             ec2_tag_auto-shutdown={{ ec2_tag_autoshutdown }}
             ec2_tag_user={{ ec2_tag_user }}
             ec2_ip_address={{ item.public_ip }}
   with_items: ec2.instances

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
   with_items: ec2.instances
   ignore_errors: true
