# Start multiple ec2 instances with instance-specific tags assigned to each
#
- hosts: localhost
  pre_tasks:
   - include_vars: ec2_vars/clusterConfig.yml
   - include_vars: ec2_vars/config.yml   
   
  tasks:
    - name: Launch Instance
      ec2:
        group_id: "{{ ec2_security_group }}"
        count: 1
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        wait: true
        region: "{{ ec2_region }}"
        keypair: "{{ ec2_keypair }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"   
        instance_tags: "{{ item.tags }}"
      register: ec2
      with_items: ec2_instances

    - name: Wait for SSH
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

    - name: Wait a little longer for centos
      pause: seconds=20

    - name: Add hosts group temporary inventory group with pem path
      add_host:
        name: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        groups: dynamic_hosts
        ansible_ssh_host: "{{ ec2.results[item.0]['instances'][0]['public_ip'] }}"
        ansible_ssh_private_key_file: '/Users/ralphh/Documents/Stuff/OHA-QA-Linux1.pem'
        ansible_ssh_user: "{{ ec2_ssh_user }}"
        ec2_vars: "{{ ec2.results[item.0]['instances'][0] }}"
        ec2_instance_ids: "{{ ec2.results[item.0]['instance_ids'] }}"
      with_indexed_items: ec2_instances

- hosts: dynamic_hosts
  tasks:
    - ping:
    