---

   - name: Define data variable
     set_fact:
         dataBoolean: "false"
     when: node_type == "master"
     
   - name: Define master variable
     set_fact:
         masterBoolean: "false"
     when: node_type == "worker"

   - name: Define masterPrivateIp
     set_fact:
         masterPrivateIp: "{{ privateIp }}"
     when: node_type == "standalone"
             
   - name: Include elasticsearch.yml template
     template: 
       src: roles/elasticsearch/templates/elasticsearch.yml.template
       dest: "{{ elastic_conf }}/elasticsearch.yml"
       
   - service: name=elasticsearch state=restarted
