
#############                    ELASTIC VARIABLES 
#ClusterType - standalone, master, worker
#elastic_type: standalone

#clusterName: BIA-QA     # elasticsearch cluster name
#cluster_name:           # ec2 cluster name

dataBoolean: "true"
masterBoolean: "true"

# Elasticsearch home directory
elastic_home: /usr/share/elasticsearch
# Elasticsearch configuration directory
elastic_conf: /etc/elasticsearch
# Elasticsearch data directory
elastic_data: /var/lib/elasticsearch
# Elasticsearch logs directory
elastic_log: /var/log/elasticsearch
# Elasticsearch work directory
elastic_work: /tmp/elasticsearch
# Elasticsearch PID directory
elastic_pid: /var/run/elasticsearch

certs_home: /usr/share/elasticsearch/certs

#s3filename: "master"

